version: '3'
services: 
  simulation-test:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./football-steps-simulations
    volumes: 
      - /home/node/app/node_modules
      - ./football-steps-simulations:/home/node/app
    command: ["npm", "run", "test"]
  api-test:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./football-steps-api
    volumes: 
      - /home/node/app/node_modules
      - ./football-steps-api:/home/node/app
    command: ["npm", "run", "test"]
  client-test:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./football-steps-client
    volumes: 
      - /home/node/app/node_modules
      - ./football-steps-client:/home/node/app
    command: ["npm", "run", "test"]