apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulations-deployment
spec: 
  replicas: 3
  selector:
    matchLabels:
      component: fbs-sim
  template:
    metadata:
      labels:
        component: fbs-sim
    spec:
      containers:
        - name: simulations
          image: jeremybamaddox/footballsteps-simulations
          ports:
            - containerPort: 4001
          env:
            - name: REDIS_HOST
              value: simulations-redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-user
            - name: MONGO_PW
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-pw
            - name: MONGO_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-account